In [1]:
# Data pre-processing
import pandas as pd
import numpy as np
import datetime as dt

# Scikit learn for mapping metrics
from sklearn.metrics import mean_squared_error

#plotting
import matplotlib.pyplot as plt
import seaborn as sns

# Statistical modelling
import scipy
import statsmodels.api as sm

In [2]:
A = pd.read_csv('Cluster_A_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
A.drop('Unnamed: 0', inplace=True, axis=1)
A['Acorn'] = 'A'

B = pd.read_csv('Cluster_B_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
B.drop('Unnamed: 0', inplace=True, axis=1)
B['Acorn'] = 'B'

C = pd.read_csv('Cluster_C_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
C.drop('Unnamed: 0', inplace=True, axis=1)
C['Acorn'] = 'C'

D = pd.read_csv('Cluster_D_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
D.drop('Unnamed: 0', inplace=True, axis=1)
D['Acorn'] = 'D'

E = pd.read_csv('Cluster_E_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
E.drop('Unnamed: 0', inplace=True, axis=1)
E['Acorn'] = 'E'

F = pd.read_csv('Cluster_F_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
F.drop('Unnamed: 0', inplace=True, axis=1)
F['Acorn'] = 'F'

G = pd.read_csv('Cluster_G_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
G.drop('Unnamed: 0', inplace=True, axis=1)
G['Acorn'] = 'G'

H = pd.read_csv('Cluster_H_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
H.drop('Unnamed: 0', inplace=True, axis=1)
H['Acorn'] = 'H'

I = pd.read_csv('Cluster_I_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
I.drop('Unnamed: 0', inplace=True, axis=1)
I['Acorn'] = 'I'

J = pd.read_csv('Cluster_J_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
J.drop('Unnamed: 0', inplace=True, axis=1)
J['Acorn'] = 'J'

K = pd.read_csv('Cluster_K_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
K.drop('Unnamed: 0', inplace=True, axis=1)
K['Acorn'] = 'K'

L = pd.read_csv('Cluster_L_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
L.drop('Unnamed: 0', inplace=True, axis=1)
L['Acorn'] = 'L'

M = pd.read_csv('Cluster_M_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
M.drop('Unnamed: 0', inplace=True, axis=1)
M['Acorn'] = 'M'

N = pd.read_csv('Cluster_N_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
N.drop('Unnamed: 0', inplace=True, axis=1)
N['Acorn'] = 'N'

O = pd.read_csv('Cluster_O_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
O.drop('Unnamed: 0', inplace=True, axis=1)
O['Acorn'] = 'O'

P = pd.read_csv('Cluster_P_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
P.drop('Unnamed: 0', inplace=True, axis=1)
P['Acorn'] = 'P'

Q = pd.read_csv('Cluster_Q_2ndLvL_predictions.csv', encoding='utf-8', sep='\t')
Q.drop('Unnamed: 0', inplace=True, axis=1)
Q['Acorn'] = 'Q'

_ = [A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q]
df = pd.concat(_)
df.sort_values(by=['DateTime', 'Acorn'], inplace=True)

In [3]:
df.head()

     y_test     y_hat             DateTime Acorn
0  0.704455  0.520650  2013-01-01 23:30:00     A
0  0.765777  0.250000  2013-01-01 23:30:00     B
0  0.250386  0.216778  2013-01-01 23:30:00     C
0  0.446137  0.390196  2013-01-01 23:30:00     D
0  0.292171  0.221971  2013-01-01 23:30:00     E

In [4]:
correlations = []
Blocks = 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q'
Blocks = Blocks.split(',')
for i in range(len(_)):
    correlations.append([np.corrcoef(_[i]['y_test'],_[i]['y_hat'])[0][1]])
correlations = np.array(correlations, dtype = float)
df_Blocks = pd.DataFrame({'CACI':Blocks, 'Correlation':correlations[:,0]})
df_Blocks

   CACI  Correlation
0     A     0.243030
1     B     0.042959
2     C     0.026257
3     D     0.016614
4     E     0.024853
5     F     0.022140
6     G     0.019096
7     H     0.029094
8     I     0.012258
9     J     0.055903
10    K     0.035063
11    L     0.011898
12    M     0.016811
13    N     0.062556
14    O     0.017805
15    P     0.024078
16    Q     0.009051

In [5]:
AA = df[(df.Acorn == 'A') | (df.Acorn == 'B') | (df.Acorn == 'C')]
RP = df[(df.Acorn == 'D') | (df.Acorn == 'E')]
CC = df[(df.Acorn == 'F') | (df.Acorn == 'G') | (df.Acorn == 'H') | (df.Acorn == 'I') | (df.Acorn == 'J')]
FS = df[(df.Acorn == 'K') | (df.Acorn == 'L') | (df.Acorn == 'M') | (df.Acorn == 'N')]
UA = df[(df.Acorn == 'O') | (df.Acorn == 'P') | (df.Acorn == 'Q')]

In [6]:
CACI = [AA, RP, CC, FS, UA]
abbrev = 'AA, RP, CC, FS, UA'
abbrev = abbrev.split(', ')
caci_cor = []
for i in range(len(CACI)):
    caci_cor.append([np.corrcoef(CACI[i]['y_test'],CACI[i]['y_hat'])[0][1]])
caci_cor = np.array(caci_cor, dtype = float)
df_CACI = pd.DataFrame({'CACI':abbrev, 'Correlation':caci_cor[:,0]})
df_CACI.head()

  CACI  Correlation
0   AA     0.040535
1   RP     0.021614
2   CC     0.057086
3   FS     0.031439
4   UA     0.018009